### ISSUE TITLE
simple-captcha validation error is not shown

### ISSUE THREAD

**Issue by eLvErDe** [django-crispy-forms/django-crispy-forms#971]
Hello,

When using a CaptchaField from simple-captcha module with crispy-forms, if I leave the field empty, or provide an invalid response, no error is displayed.
If I disable crispy-forms, it works.

I looked into the generated HTML and found the entry:
```html
<span id="error_1_id_captcha" class="invalid-feedback"><strong>Invalid response</strong</span>
```

The problem is, this CSS class has a "display: none" prop... So I overloaded my global CSS with the following:

```css
/* Workaround a bug in crispy-forms not showing validation error from simple-captcha */
.invalid-feedback {
    display: block;
}
```

And the validation error is now displayed successfully.

Best regards, Adam.
