### ISSUE TITLE
pre-commit

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#993]
Not really an issue but a note for the future; a discussion you could say 😄 

I've had a play with pre-commit and I think we need the `.pre-commit-config.yaml` to look something like the below. At the moment we've got a few pull requests open which once merged will make it much easier to test. 

It should also come with some additional notes on how to use it. Probably in the contribution section of the docs. 

```
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  -   repo: https://github.com/timothycrosley/isort
      rev: 4.3.21-2
      hooks:
      - id: isort
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
      - id: flake8

```
